

(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list
   'package-archives
   '("melpa" . "https://melpa.org/packages/")
   t)
  (package-initialize))

;; (require 'ert)
(add-to-list 'load-path "~/.emacs.d/config/")
(require 'kodi-remote)
;; (setq kodi-host-name "localhost:8080")

(ert-deftest fullscreen-test ()
  (let ((kodi-host-name "localhost:8080"))
    (should (booleanp (kodi-remote-is-fullscreen)))))

(ert-deftest volume-test ()
  (let ((kodi-host-name "localhost:8080"))
    (should (integerp (kodi-remote-get-volume)))))

(ert-deftest volume-complex-test ()
  (let ((kodi-host-name "localhost:8080"))
    (dotimes (x 20) (kodi-remote-volume-decrease))
    (should (eql (kodi-remote-get-volume )0))
    (dotimes (x 9) (kodi-remote-volume-increase)(sit-for 0.05))
    (should (eql (kodi-remote-get-volume )90))))


(ert-deftest active-window-is-home-test ()
  (let ((kodi-host-name "localhost:8080"))
    (should (string-equal "Home" (kodi-remote-get-active-window)))))

(ert-deftest series-window-open-test ()
  (let ((kodi-host-name "localhost:8080"))
    (kodi-remote-series)
    (should (string-equal "*kodi-remote-series*" (buffer-name)))))


(ert-deftest playlist-window-open-test ()
  (let ((kodi-host-name "localhost:8080"))
    (kodi-remote-playlist)
    (should (string-equal "*kodi-remote-playlist*" (buffer-name)))))

(ert-deftest music-window-open-test ()
  (let ((kodi-host-name "localhost:8080"))
    ;; (setq kodi-host-name "localhost:8080")
    (kodi-remote-music)
    (should (equal [("Artists" 30 t)] tabulated-list-format))
    (should (string-equal "*kodi-remote-music*" (buffer-name)))
    (should (string-equal "Ash Turner" (buffer-substring 1 (buffer-size))))
    (push-button)
    (should (equal [("Songs" 30 t)] tabulated-list-format))
    (should (string-equal "*kodi-remote-songs*" (buffer-name)))
    (should (string-equal "Leaping Leopards\nSt Columba's Twist\nTrichotomy\nLow Pressure" (buffer-substring 1 (buffer-size))))))


(ert-deftest playlist-complex-test ()
  (let ((kodi-host-name "localhost:8080"))
    (kodi-remote-playlist)
    ;; (kodi-remote-playlist-clear)
    (kodi-remote-playlist-add-url "http://example.org/video1.avi")
    (sit-for 0.4)
    (kodi-remote-playlist-add-url "http://example.org/video2.avi")
    (sit-for 0.4)
    (kodi-remote-playlist-add-url "http://example.org/video3.avi")
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video1.avi\nvideo2.avi\nvideo3.avi"))
    (kodi-remote-playlist-move-down)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video2.avi\nvideo1.avi\nvideo3.avi"))
    (kodi-remote-playlist-move-down)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video1.avi\nvideo2.avi\nvideo3.avi"))
    (kodi-remote-playlist-move-up)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video1.avi\nvideo2.avi\nvideo3.avi"))
    (next-line)
    (kodi-remote-playlist-move-up)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video2.avi\nvideo1.avi\nvideo3.avi"))
    (kodi-remote-playlist-remove)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-substring 1 (buffer-size)) "video1.avi\nvideo3.avi"))
    (kodi-remote-playlist-clear)
    (sit-for 0.4)
    (revert-buffer)
    (should (equal (buffer-size) 0))))
